import Foundation

/// One row in either the "Where Received came from" or "Top spending
/// categories" lists. Pure name-amount pair.
struct CycleBreakdownRow: Identifiable, Hashable, Equatable {
    let name: String
    let amount: Decimal

    var id: String { name }
}

/// Full cycle detail summary. Generated by CycleDetailService.aggregate
/// from a single transactions fetch + the user's categories.
///
/// `receivedBySource` is uncapped, sorted descending by amount.
/// `topSpending` is capped at 5, sorted descending by amount.
struct CycleDetailSummary: Equatable {
    let cycle: Cycle
    let totalReceived: Decimal
    let totalSpent: Decimal
    let receivedBySource: [CycleBreakdownRow]
    let topSpending: [CycleBreakdownRow]

    /// Net cash flow: received minus spent.
    var net: Decimal { totalReceived - totalSpent }

    /// Whether both breakdown lists are empty (triggers page-level empty state).
    var isEmpty: Bool {
        receivedBySource.isEmpty && topSpending.isEmpty
    }
}
