import Foundation

/// Categorical type of insight.
/// Mirrors web's InsightKind type union exactly.
/// Use rawValue for Codable round-trip with the JSONB column.
enum InsightKind: String, Codable, CaseIterable, Equatable {
    case budgetPacing       = "budget_pacing"
    case categoryTrend      = "category_trend"
    case goalNudge          = "goal_nudge"
    case streakBoost        = "streak_boost"
    case subscriptionAlert  = "subscription_alert"
    case reflection         = "reflection"
    case quickWin           = "quick_win"
}

/// Accent color treatment for the insight banner.
enum InsightAccent: String, Codable, CaseIterable, Equatable {
    case green
    case amber
    case red
    case blue
    case neutral
}

/// Optional numeric callout (e.g. "Spent today: ₵42").
struct InsightStat: Codable, Equatable {
    let label: String
    let value: String
}

/// AI-generated insight content (the inside of the JSONB column).
/// Generated by Claude Sonnet from per-user financial context;
/// validated server-side (headline ≤ 12 words).
struct DailyInsight: Codable, Equatable {
    let kind: InsightKind
    let headline: String
    let body: String
    let accent: InsightAccent
    let stat: InsightStat?
    /// Lucide icon name (e.g. "TrendingUp", "Flame", "Sparkles").
    /// Resolve to SF Symbol via InsightSymbol.resolve(_:).
    let icon: String?
}

/// Database row from the daily_insights table.
/// One row per (user_id, insight_date). insight_data is the JSONB column
/// containing the DailyInsight struct above.
struct DailyInsightRow: Codable, Identifiable, Equatable {
    let id: UUID
    let userId: UUID
    let insightDate: String   // YYYY-MM-DD
    let insightData: DailyInsight
    let generatedAt: Date
    let dismissedAt: Date?

    enum CodingKeys: String, CodingKey {
        case id
        case userId      = "user_id"
        case insightDate = "insight_date"
        case insightData = "insight_data"
        case generatedAt = "generated_at"
        case dismissedAt = "dismissed_at"
    }
}
